In [39]:
import pandas
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta

In [40]:
df = pandas.read_csv("MU5735-Flightradar24-Granular-Data.csv")
df['time'] = [_.split("Z")[0] for _ in df['time']]
df["time"] = pandas.to_datetime(df["time"], format='%Y-%m-%d %H:%M:%S')
df = df.set_index("time")
df = df[df.index>df.index[-1]-timedelta(minutes=3)]

In [58]:
fig = make_subplots(rows=4)
fig.update_layout(width=800, height=600, title="#MU5735 Last 3 minutes")
fig.add_trace(go.Scatter(x=df.index, y=df['altitude'], name="Altitude ft"), row=1, col=1)
# fig.update_yaxes(title_text="Altitude ft", row=1, col=1)
fig.add_trace(go.Scatter(x=df.index, y=df['speed'], name="GPS speed kt"), row=2, col=1)
# fig.update_yaxes(title_text="GPS speed kt", row=2, col=1)
fig.add_trace(go.Scatter(x=df.index, y=df['vspeed'], name="VV ft/min"), row=3, col=1)
# fig.update_yaxes(title_text="VV ft/min", row=3, col=1)
fig.add_trace(go.Scatter(x=df.index, y=df['track'], name="Track angle deg"), row=4, col=1)
# fig.update_yaxes(title_text="Track angle deg", row=4, col=1)
fig.write_html("mu5735.html")

In [27]:
df

,hex,callsign,latitude,longitude,no_position,altitude,squawk,speed,track,vspeed
time,,,,,,,,,,
2022-03-21 05:16:36,0x780db8,NaN,0.00000,0.00000,N,7850,0,174,214,1792
2022-03-21 05:16:42,0x780db8,CES5735,25.09502,102.91204,P,8100,0,178,218,2624
2022-03-21 05:16:48,0x780db8,CES5735,25.09154,102.90868,P,8300,2101,179,222,2048
2022-03-21 05:16:53,0x780db8,CES5735,25.08835,102.90505,P,8400,2101,183,227,1024
2022-03-21 05:16:58,0x780db8,NaN,0.00000,0.00000,N,8450,0,189,229,1152
...,...,...,...,...,...,...,...,...,...,...
2022-03-21 06:22:01,0x780db8,CES5735,23.30940,111.02875,P,8025,0,531,84,7360
2022-03-21 06:22:05,0x780db8,CES5735,23.30974,111.04041,P,8600,0,507,88,8448
2022-03-21 06:22:21,0x780db8,CES5735,23.33031,111.07468,P,8175,0,446,79,-13248
2022-03-21 06:22:31,0x780db8,CES5735,23.33533,111.09754,P,4375,0,442,73,-26752
2022-03-21 06:22:35,0x780db8,CES5735,23.33752,111.10558,P,3225,0,376,87,-30976